// Code generated by ent, DO NOT EDIT.

package objectversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/burrow/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// ObjectID applies equality check predicate on the "object_id" field. It's identical to ObjectIDEQ.
func ObjectID(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldObjectID, v))
}

// BlobID applies equality check predicate on the "blob_id" field. It's identical to BlobIDEQ.
func BlobID(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldBlobID, v))
}

// RestoredFromVersionID applies equality check predicate on the "restored_from_version_id" field. It's identical to RestoredFromVersionIDEQ.
func RestoredFromVersionID(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldRestoredFromVersionID, v))
}

// CapturedAt applies equality check predicate on the "captured_at" field. It's identical to CapturedAtEQ.
func CapturedAt(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldCapturedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldUpdatedAt, v))
}

// ObjectIDEQ applies the EQ predicate on the "object_id" field.
func ObjectIDEQ(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldObjectID, v))
}

// ObjectIDNEQ applies the NEQ predicate on the "object_id" field.
func ObjectIDNEQ(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldObjectID, v))
}

// ObjectIDIn applies the In predicate on the "object_id" field.
func ObjectIDIn(vs ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldObjectID, vs...))
}

// ObjectIDNotIn applies the NotIn predicate on the "object_id" field.
func ObjectIDNotIn(vs ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldObjectID, vs...))
}

// ObjectIDGT applies the GT predicate on the "object_id" field.
func ObjectIDGT(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldObjectID, v))
}

// ObjectIDGTE applies the GTE predicate on the "object_id" field.
func ObjectIDGTE(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldObjectID, v))
}

// ObjectIDLT applies the LT predicate on the "object_id" field.
func ObjectIDLT(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldObjectID, v))
}

// ObjectIDLTE applies the LTE predicate on the "object_id" field.
func ObjectIDLTE(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldObjectID, v))
}

// ObjectIDContains applies the Contains predicate on the "object_id" field.
func ObjectIDContains(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContains(FieldObjectID, v))
}

// ObjectIDHasPrefix applies the HasPrefix predicate on the "object_id" field.
func ObjectIDHasPrefix(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldHasPrefix(FieldObjectID, v))
}

// ObjectIDHasSuffix applies the HasSuffix predicate on the "object_id" field.
func ObjectIDHasSuffix(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldHasSuffix(FieldObjectID, v))
}

// ObjectIDEqualFold applies the EqualFold predicate on the "object_id" field.
func ObjectIDEqualFold(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEqualFold(FieldObjectID, v))
}

// ObjectIDContainsFold applies the ContainsFold predicate on the "object_id" field.
func ObjectIDContainsFold(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContainsFold(FieldObjectID, v))
}

// BlobIDEQ applies the EQ predicate on the "blob_id" field.
func BlobIDEQ(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldBlobID, v))
}

// BlobIDNEQ applies the NEQ predicate on the "blob_id" field.
func BlobIDNEQ(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldBlobID, v))
}

// BlobIDIn applies the In predicate on the "blob_id" field.
func BlobIDIn(vs ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldBlobID, vs...))
}

// BlobIDNotIn applies the NotIn predicate on the "blob_id" field.
func BlobIDNotIn(vs ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldBlobID, vs...))
}

// BlobIDGT applies the GT predicate on the "blob_id" field.
func BlobIDGT(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldBlobID, v))
}

// BlobIDGTE applies the GTE predicate on the "blob_id" field.
func BlobIDGTE(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldBlobID, v))
}

// BlobIDLT applies the LT predicate on the "blob_id" field.
func BlobIDLT(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldBlobID, v))
}

// BlobIDLTE applies the LTE predicate on the "blob_id" field.
func BlobIDLTE(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldBlobID, v))
}

// BlobIDContains applies the Contains predicate on the "blob_id" field.
func BlobIDContains(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContains(FieldBlobID, v))
}

// BlobIDHasPrefix applies the HasPrefix predicate on the "blob_id" field.
func BlobIDHasPrefix(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldHasPrefix(FieldBlobID, v))
}

// BlobIDHasSuffix applies the HasSuffix predicate on the "blob_id" field.
func BlobIDHasSuffix(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldHasSuffix(FieldBlobID, v))
}

// BlobIDEqualFold applies the EqualFold predicate on the "blob_id" field.
func BlobIDEqualFold(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEqualFold(FieldBlobID, v))
}

// BlobIDContainsFold applies the ContainsFold predicate on the "blob_id" field.
func BlobIDContainsFold(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContainsFold(FieldBlobID, v))
}

// RestoredFromVersionIDEQ applies the EQ predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDEQ(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDNEQ applies the NEQ predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDNEQ(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDIn applies the In predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDIn(vs ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldRestoredFromVersionID, vs...))
}

// RestoredFromVersionIDNotIn applies the NotIn predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDNotIn(vs ...string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldRestoredFromVersionID, vs...))
}

// RestoredFromVersionIDGT applies the GT predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDGT(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDGTE applies the GTE predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDGTE(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDLT applies the LT predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDLT(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDLTE applies the LTE predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDLTE(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDContains applies the Contains predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDContains(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContains(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDHasPrefix applies the HasPrefix predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDHasPrefix(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldHasPrefix(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDHasSuffix applies the HasSuffix predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDHasSuffix(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldHasSuffix(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDIsNil applies the IsNil predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDIsNil() predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIsNull(FieldRestoredFromVersionID))
}

// RestoredFromVersionIDNotNil applies the NotNil predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDNotNil() predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotNull(FieldRestoredFromVersionID))
}

// RestoredFromVersionIDEqualFold applies the EqualFold predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDEqualFold(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEqualFold(FieldRestoredFromVersionID, v))
}

// RestoredFromVersionIDContainsFold applies the ContainsFold predicate on the "restored_from_version_id" field.
func RestoredFromVersionIDContainsFold(v string) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldContainsFold(FieldRestoredFromVersionID, v))
}

// CapturedAtEQ applies the EQ predicate on the "captured_at" field.
func CapturedAtEQ(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtNEQ applies the NEQ predicate on the "captured_at" field.
func CapturedAtNEQ(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNEQ(FieldCapturedAt, v))
}

// CapturedAtIn applies the In predicate on the "captured_at" field.
func CapturedAtIn(vs ...time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldIn(FieldCapturedAt, vs...))
}

// CapturedAtNotIn applies the NotIn predicate on the "captured_at" field.
func CapturedAtNotIn(vs ...time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldNotIn(FieldCapturedAt, vs...))
}

// CapturedAtGT applies the GT predicate on the "captured_at" field.
func CapturedAtGT(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGT(FieldCapturedAt, v))
}

// CapturedAtGTE applies the GTE predicate on the "captured_at" field.
func CapturedAtGTE(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldGTE(FieldCapturedAt, v))
}

// CapturedAtLT applies the LT predicate on the "captured_at" field.
func CapturedAtLT(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLT(FieldCapturedAt, v))
}

// CapturedAtLTE applies the LTE predicate on the "captured_at" field.
func CapturedAtLTE(v time.Time) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.FieldLTE(FieldCapturedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ObjectVersion) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ObjectVersion) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ObjectVersion) predicate.ObjectVersion {
	return predicate.ObjectVersion(sql.NotPredicates(p))
}
