// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/object"
)

// ObjectCreate is the builder for creating a Object entity.
type ObjectCreate struct {
	config
	mutation *ObjectMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ObjectCreate) SetCreatedAt(v time.Time) *ObjectCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableCreatedAt(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ObjectCreate) SetUpdatedAt(v time.Time) *ObjectCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableUpdatedAt(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ObjectCreate) SetSourceID(v string) *ObjectCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ObjectCreate) SetKind(v string) *ObjectCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *ObjectCreate) SetExternalID(v string) *ObjectCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_c *ObjectCreate) SetFirstSeenAt(v time.Time) *ObjectCreate {
	_c.mutation.SetFirstSeenAt(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *ObjectCreate) SetLastSeenAt(v time.Time) *ObjectCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetDeletedAtSource sets the "deleted_at_source" field.
func (_c *ObjectCreate) SetDeletedAtSource(v time.Time) *ObjectCreate {
	_c.mutation.SetDeletedAtSource(v)
	return _c
}

// SetNillableDeletedAtSource sets the "deleted_at_source" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableDeletedAtSource(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetDeletedAtSource(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ObjectCreate) SetID(v string) *ObjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ObjectMutation object of the builder.
func (_c *ObjectCreate) Mutation() *ObjectMutation {
	return _c.mutation
}

// Save creates the Object in the database.
func (_c *ObjectCreate) Save(ctx context.Context) (*Object, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObjectCreate) SaveX(ctx context.Context) *Object {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObjectCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := object.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := object.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObjectCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Object.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Object.updated_at"`)}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "Object.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := object.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "Object.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Object.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := object.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Object.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "Object.external_id"`)}
	}
	if v, ok := _c.mutation.ExternalID(); ok {
		if err := object.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Object.external_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FirstSeenAt(); !ok {
		return &ValidationError{Name: "first_seen_at", err: errors.New(`ent: missing required field "Object.first_seen_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "Object.last_seen_at"`)}
	}
	return nil
}

func (_c *ObjectCreate) sqlSave(ctx context.Context) (*Object, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Object.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObjectCreate) createSpec() (*Object, *sqlgraph.CreateSpec) {
	var (
		_node = &Object{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(object.Table, sqlgraph.NewFieldSpec(object.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(object.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(object.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(object.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(object.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(object.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.FirstSeenAt(); ok {
		_spec.SetField(object.FieldFirstSeenAt, field.TypeTime, value)
		_node.FirstSeenAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(object.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.DeletedAtSource(); ok {
		_spec.SetField(object.FieldDeletedAtSource, field.TypeTime, value)
		_node.DeletedAtSource = &value
	}
	return _node, _spec
}

// ObjectCreateBulk is the builder for creating many Object entities in bulk.
type ObjectCreateBulk struct {
	config
	err      error
	builders []*ObjectCreate
}

// Save creates the Object entities in the database.
func (_c *ObjectCreateBulk) Save(ctx context.Context) ([]*Object, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Object, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObjectCreateBulk) SaveX(ctx context.Context) []*Object {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
