// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/object"
	"github.com/omkar273/burrow/packages/engine/ent/objectalias"
	"github.com/omkar273/burrow/packages/engine/ent/objectversion"
	"github.com/omkar273/burrow/packages/engine/ent/predicate"
)

// ObjectUpdate is the builder for updating Object entities.
type ObjectUpdate struct {
	config
	hooks    []Hook
	mutation *ObjectMutation
}

// Where appends a list predicates to the ObjectUpdate builder.
func (_u *ObjectUpdate) Where(ps ...predicate.Object) *ObjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectUpdate) SetUpdatedAt(v time.Time) *ObjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *ObjectUpdate) SetFirstSeenAt(v time.Time) *ObjectUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *ObjectUpdate) SetNillableFirstSeenAt(v *time.Time) *ObjectUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ObjectUpdate) SetLastSeenAt(v time.Time) *ObjectUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ObjectUpdate) SetNillableLastSeenAt(v *time.Time) *ObjectUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetDeletedAtSource sets the "deleted_at_source" field.
func (_u *ObjectUpdate) SetDeletedAtSource(v time.Time) *ObjectUpdate {
	_u.mutation.SetDeletedAtSource(v)
	return _u
}

// SetNillableDeletedAtSource sets the "deleted_at_source" field if the given value is not nil.
func (_u *ObjectUpdate) SetNillableDeletedAtSource(v *time.Time) *ObjectUpdate {
	if v != nil {
		_u.SetDeletedAtSource(*v)
	}
	return _u
}

// ClearDeletedAtSource clears the value of the "deleted_at_source" field.
func (_u *ObjectUpdate) ClearDeletedAtSource() *ObjectUpdate {
	_u.mutation.ClearDeletedAtSource()
	return _u
}

// AddAliasIDs adds the "aliases" edge to the ObjectAlias entity by IDs.
func (_u *ObjectUpdate) AddAliasIDs(ids ...string) *ObjectUpdate {
	_u.mutation.AddAliasIDs(ids...)
	return _u
}

// AddAliases adds the "aliases" edges to the ObjectAlias entity.
func (_u *ObjectUpdate) AddAliases(v ...*ObjectAlias) *ObjectUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAliasIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the ObjectVersion entity by IDs.
func (_u *ObjectUpdate) AddVersionIDs(ids ...string) *ObjectUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the ObjectVersion entity.
func (_u *ObjectUpdate) AddVersions(v ...*ObjectVersion) *ObjectUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the ObjectMutation object of the builder.
func (_u *ObjectUpdate) Mutation() *ObjectMutation {
	return _u.mutation
}

// ClearAliases clears all "aliases" edges to the ObjectAlias entity.
func (_u *ObjectUpdate) ClearAliases() *ObjectUpdate {
	_u.mutation.ClearAliases()
	return _u
}

// RemoveAliasIDs removes the "aliases" edge to ObjectAlias entities by IDs.
func (_u *ObjectUpdate) RemoveAliasIDs(ids ...string) *ObjectUpdate {
	_u.mutation.RemoveAliasIDs(ids...)
	return _u
}

// RemoveAliases removes "aliases" edges to ObjectAlias entities.
func (_u *ObjectUpdate) RemoveAliases(v ...*ObjectAlias) *ObjectUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAliasIDs(ids...)
}

// ClearVersions clears all "versions" edges to the ObjectVersion entity.
func (_u *ObjectUpdate) ClearVersions() *ObjectUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to ObjectVersion entities by IDs.
func (_u *ObjectUpdate) RemoveVersionIDs(ids ...string) *ObjectUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to ObjectVersion entities.
func (_u *ObjectUpdate) RemoveVersions(v ...*ObjectVersion) *ObjectUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := object.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObjectUpdate) check() error {
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Object.source"`)
	}
	return nil
}

func (_u *ObjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(object.Table, object.Columns, sqlgraph.NewFieldSpec(object.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(object.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(object.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(object.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAtSource(); ok {
		_spec.SetField(object.FieldDeletedAtSource, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtSourceCleared() {
		_spec.ClearField(object.FieldDeletedAtSource, field.TypeTime)
	}
	if _u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.AliasesTable,
			Columns: []string{object.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAliasesIDs(); len(nodes) > 0 && !_u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.AliasesTable,
			Columns: []string{object.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AliasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.AliasesTable,
			Columns: []string{object.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.VersionsTable,
			Columns: []string{object.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.VersionsTable,
			Columns: []string{object.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.VersionsTable,
			Columns: []string{object.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{object.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObjectUpdateOne is the builder for updating a single Object entity.
type ObjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ObjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectUpdateOne) SetUpdatedAt(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *ObjectUpdateOne) SetFirstSeenAt(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *ObjectUpdateOne) SetNillableFirstSeenAt(v *time.Time) *ObjectUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ObjectUpdateOne) SetLastSeenAt(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ObjectUpdateOne) SetNillableLastSeenAt(v *time.Time) *ObjectUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetDeletedAtSource sets the "deleted_at_source" field.
func (_u *ObjectUpdateOne) SetDeletedAtSource(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetDeletedAtSource(v)
	return _u
}

// SetNillableDeletedAtSource sets the "deleted_at_source" field if the given value is not nil.
func (_u *ObjectUpdateOne) SetNillableDeletedAtSource(v *time.Time) *ObjectUpdateOne {
	if v != nil {
		_u.SetDeletedAtSource(*v)
	}
	return _u
}

// ClearDeletedAtSource clears the value of the "deleted_at_source" field.
func (_u *ObjectUpdateOne) ClearDeletedAtSource() *ObjectUpdateOne {
	_u.mutation.ClearDeletedAtSource()
	return _u
}

// AddAliasIDs adds the "aliases" edge to the ObjectAlias entity by IDs.
func (_u *ObjectUpdateOne) AddAliasIDs(ids ...string) *ObjectUpdateOne {
	_u.mutation.AddAliasIDs(ids...)
	return _u
}

// AddAliases adds the "aliases" edges to the ObjectAlias entity.
func (_u *ObjectUpdateOne) AddAliases(v ...*ObjectAlias) *ObjectUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAliasIDs(ids...)
}

// AddVersionIDs adds the "versions" edge to the ObjectVersion entity by IDs.
func (_u *ObjectUpdateOne) AddVersionIDs(ids ...string) *ObjectUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "versions" edges to the ObjectVersion entity.
func (_u *ObjectUpdateOne) AddVersions(v ...*ObjectVersion) *ObjectUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the ObjectMutation object of the builder.
func (_u *ObjectUpdateOne) Mutation() *ObjectMutation {
	return _u.mutation
}

// ClearAliases clears all "aliases" edges to the ObjectAlias entity.
func (_u *ObjectUpdateOne) ClearAliases() *ObjectUpdateOne {
	_u.mutation.ClearAliases()
	return _u
}

// RemoveAliasIDs removes the "aliases" edge to ObjectAlias entities by IDs.
func (_u *ObjectUpdateOne) RemoveAliasIDs(ids ...string) *ObjectUpdateOne {
	_u.mutation.RemoveAliasIDs(ids...)
	return _u
}

// RemoveAliases removes "aliases" edges to ObjectAlias entities.
func (_u *ObjectUpdateOne) RemoveAliases(v ...*ObjectAlias) *ObjectUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAliasIDs(ids...)
}

// ClearVersions clears all "versions" edges to the ObjectVersion entity.
func (_u *ObjectUpdateOne) ClearVersions() *ObjectUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "versions" edge to ObjectVersion entities by IDs.
func (_u *ObjectUpdateOne) RemoveVersionIDs(ids ...string) *ObjectUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "versions" edges to ObjectVersion entities.
func (_u *ObjectUpdateOne) RemoveVersions(v ...*ObjectVersion) *ObjectUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Where appends a list predicates to the ObjectUpdate builder.
func (_u *ObjectUpdateOne) Where(ps ...predicate.Object) *ObjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObjectUpdateOne) Select(field string, fields ...string) *ObjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Object entity.
func (_u *ObjectUpdateOne) Save(ctx context.Context) (*Object, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectUpdateOne) SaveX(ctx context.Context) *Object {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := object.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObjectUpdateOne) check() error {
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Object.source"`)
	}
	return nil
}

func (_u *ObjectUpdateOne) sqlSave(ctx context.Context) (_node *Object, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(object.Table, object.Columns, sqlgraph.NewFieldSpec(object.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Object.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, object.FieldID)
		for _, f := range fields {
			if !object.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != object.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(object.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(object.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(object.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAtSource(); ok {
		_spec.SetField(object.FieldDeletedAtSource, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtSourceCleared() {
		_spec.ClearField(object.FieldDeletedAtSource, field.TypeTime)
	}
	if _u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.AliasesTable,
			Columns: []string{object.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAliasesIDs(); len(nodes) > 0 && !_u.mutation.AliasesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.AliasesTable,
			Columns: []string{object.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AliasesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.AliasesTable,
			Columns: []string{object.AliasesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.VersionsTable,
			Columns: []string{object.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.VersionsTable,
			Columns: []string{object.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   object.VersionsTable,
			Columns: []string{object.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Object{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{object.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
