// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/object"
	"github.com/omkar273/burrow/packages/engine/ent/predicate"
)

// ObjectUpdate is the builder for updating Object entities.
type ObjectUpdate struct {
	config
	hooks    []Hook
	mutation *ObjectMutation
}

// Where appends a list predicates to the ObjectUpdate builder.
func (_u *ObjectUpdate) Where(ps ...predicate.Object) *ObjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectUpdate) SetUpdatedAt(v time.Time) *ObjectUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *ObjectUpdate) SetFirstSeenAt(v time.Time) *ObjectUpdate {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *ObjectUpdate) SetNillableFirstSeenAt(v *time.Time) *ObjectUpdate {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ObjectUpdate) SetLastSeenAt(v time.Time) *ObjectUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ObjectUpdate) SetNillableLastSeenAt(v *time.Time) *ObjectUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetDeletedAtSource sets the "deleted_at_source" field.
func (_u *ObjectUpdate) SetDeletedAtSource(v time.Time) *ObjectUpdate {
	_u.mutation.SetDeletedAtSource(v)
	return _u
}

// SetNillableDeletedAtSource sets the "deleted_at_source" field if the given value is not nil.
func (_u *ObjectUpdate) SetNillableDeletedAtSource(v *time.Time) *ObjectUpdate {
	if v != nil {
		_u.SetDeletedAtSource(*v)
	}
	return _u
}

// ClearDeletedAtSource clears the value of the "deleted_at_source" field.
func (_u *ObjectUpdate) ClearDeletedAtSource() *ObjectUpdate {
	_u.mutation.ClearDeletedAtSource()
	return _u
}

// Mutation returns the ObjectMutation object of the builder.
func (_u *ObjectUpdate) Mutation() *ObjectMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObjectUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := object.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ObjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(object.Table, object.Columns, sqlgraph.NewFieldSpec(object.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(object.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(object.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(object.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAtSource(); ok {
		_spec.SetField(object.FieldDeletedAtSource, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtSourceCleared() {
		_spec.ClearField(object.FieldDeletedAtSource, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{object.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObjectUpdateOne is the builder for updating a single Object entity.
type ObjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ObjectMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectUpdateOne) SetUpdatedAt(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFirstSeenAt sets the "first_seen_at" field.
func (_u *ObjectUpdateOne) SetFirstSeenAt(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetFirstSeenAt(v)
	return _u
}

// SetNillableFirstSeenAt sets the "first_seen_at" field if the given value is not nil.
func (_u *ObjectUpdateOne) SetNillableFirstSeenAt(v *time.Time) *ObjectUpdateOne {
	if v != nil {
		_u.SetFirstSeenAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *ObjectUpdateOne) SetLastSeenAt(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *ObjectUpdateOne) SetNillableLastSeenAt(v *time.Time) *ObjectUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetDeletedAtSource sets the "deleted_at_source" field.
func (_u *ObjectUpdateOne) SetDeletedAtSource(v time.Time) *ObjectUpdateOne {
	_u.mutation.SetDeletedAtSource(v)
	return _u
}

// SetNillableDeletedAtSource sets the "deleted_at_source" field if the given value is not nil.
func (_u *ObjectUpdateOne) SetNillableDeletedAtSource(v *time.Time) *ObjectUpdateOne {
	if v != nil {
		_u.SetDeletedAtSource(*v)
	}
	return _u
}

// ClearDeletedAtSource clears the value of the "deleted_at_source" field.
func (_u *ObjectUpdateOne) ClearDeletedAtSource() *ObjectUpdateOne {
	_u.mutation.ClearDeletedAtSource()
	return _u
}

// Mutation returns the ObjectMutation object of the builder.
func (_u *ObjectUpdateOne) Mutation() *ObjectMutation {
	return _u.mutation
}

// Where appends a list predicates to the ObjectUpdate builder.
func (_u *ObjectUpdateOne) Where(ps ...predicate.Object) *ObjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObjectUpdateOne) Select(field string, fields ...string) *ObjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Object entity.
func (_u *ObjectUpdateOne) Save(ctx context.Context) (*Object, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectUpdateOne) SaveX(ctx context.Context) *Object {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := object.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ObjectUpdateOne) sqlSave(ctx context.Context) (_node *Object, err error) {
	_spec := sqlgraph.NewUpdateSpec(object.Table, object.Columns, sqlgraph.NewFieldSpec(object.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Object.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, object.FieldID)
		for _, f := range fields {
			if !object.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != object.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(object.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FirstSeenAt(); ok {
		_spec.SetField(object.FieldFirstSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(object.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAtSource(); ok {
		_spec.SetField(object.FieldDeletedAtSource, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtSourceCleared() {
		_spec.ClearField(object.FieldDeletedAtSource, field.TypeTime)
	}
	_node = &Object{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{object.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
