// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/burrow/packages/engine/ent/blob"
	"github.com/omkar273/burrow/packages/engine/ent/object"
	"github.com/omkar273/burrow/packages/engine/ent/objectversion"
)

// ObjectVersion is the model entity for the ObjectVersion schema.
type ObjectVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ObjectID holds the value of the "object_id" field.
	ObjectID string `json:"object_id,omitempty"`
	// BlobID holds the value of the "blob_id" field.
	BlobID string `json:"blob_id,omitempty"`
	// RestoredFromVersionID holds the value of the "restored_from_version_id" field.
	RestoredFromVersionID *string `json:"restored_from_version_id,omitempty"`
	// CapturedAt holds the value of the "captured_at" field.
	CapturedAt time.Time `json:"captured_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ObjectVersionQuery when eager-loading is set.
	Edges        ObjectVersionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ObjectVersionEdges holds the relations/edges for other nodes in the graph.
type ObjectVersionEdges struct {
	// Object holds the value of the object edge.
	Object *Object `json:"object,omitempty"`
	// Blob holds the value of the blob edge.
	Blob *Blob `json:"blob,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ObjectOrErr returns the Object value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ObjectVersionEdges) ObjectOrErr() (*Object, error) {
	if e.Object != nil {
		return e.Object, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: object.Label}
	}
	return nil, &NotLoadedError{edge: "object"}
}

// BlobOrErr returns the Blob value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ObjectVersionEdges) BlobOrErr() (*Blob, error) {
	if e.Blob != nil {
		return e.Blob, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: blob.Label}
	}
	return nil, &NotLoadedError{edge: "blob"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ObjectVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case objectversion.FieldID, objectversion.FieldObjectID, objectversion.FieldBlobID, objectversion.FieldRestoredFromVersionID:
			values[i] = new(sql.NullString)
		case objectversion.FieldCreatedAt, objectversion.FieldUpdatedAt, objectversion.FieldCapturedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ObjectVersion fields.
func (_m *ObjectVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case objectversion.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case objectversion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case objectversion.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case objectversion.FieldObjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_id", values[i])
			} else if value.Valid {
				_m.ObjectID = value.String
			}
		case objectversion.FieldBlobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blob_id", values[i])
			} else if value.Valid {
				_m.BlobID = value.String
			}
		case objectversion.FieldRestoredFromVersionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field restored_from_version_id", values[i])
			} else if value.Valid {
				_m.RestoredFromVersionID = new(string)
				*_m.RestoredFromVersionID = value.String
			}
		case objectversion.FieldCapturedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field captured_at", values[i])
			} else if value.Valid {
				_m.CapturedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ObjectVersion.
// This includes values selected through modifiers, order, etc.
func (_m *ObjectVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryObject queries the "object" edge of the ObjectVersion entity.
func (_m *ObjectVersion) QueryObject() *ObjectQuery {
	return NewObjectVersionClient(_m.config).QueryObject(_m)
}

// QueryBlob queries the "blob" edge of the ObjectVersion entity.
func (_m *ObjectVersion) QueryBlob() *BlobQuery {
	return NewObjectVersionClient(_m.config).QueryBlob(_m)
}

// Update returns a builder for updating this ObjectVersion.
// Note that you need to call ObjectVersion.Unwrap() before calling this method if this ObjectVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ObjectVersion) Update() *ObjectVersionUpdateOne {
	return NewObjectVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ObjectVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ObjectVersion) Unwrap() *ObjectVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ObjectVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ObjectVersion) String() string {
	var builder strings.Builder
	builder.WriteString("ObjectVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("object_id=")
	builder.WriteString(_m.ObjectID)
	builder.WriteString(", ")
	builder.WriteString("blob_id=")
	builder.WriteString(_m.BlobID)
	builder.WriteString(", ")
	if v := _m.RestoredFromVersionID; v != nil {
		builder.WriteString("restored_from_version_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("captured_at=")
	builder.WriteString(_m.CapturedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ObjectVersions is a parsable slice of ObjectVersion.
type ObjectVersions []*ObjectVersion
