// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/objectalias"
	"github.com/omkar273/burrow/packages/engine/ent/predicate"
)

// ObjectAliasDelete is the builder for deleting a ObjectAlias entity.
type ObjectAliasDelete struct {
	config
	hooks    []Hook
	mutation *ObjectAliasMutation
}

// Where appends a list predicates to the ObjectAliasDelete builder.
func (_d *ObjectAliasDelete) Where(ps ...predicate.ObjectAlias) *ObjectAliasDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ObjectAliasDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ObjectAliasDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ObjectAliasDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(objectalias.Table, sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ObjectAliasDeleteOne is the builder for deleting a single ObjectAlias entity.
type ObjectAliasDeleteOne struct {
	_d *ObjectAliasDelete
}

// Where appends a list predicates to the ObjectAliasDelete builder.
func (_d *ObjectAliasDeleteOne) Where(ps ...predicate.ObjectAlias) *ObjectAliasDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ObjectAliasDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{objectalias.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ObjectAliasDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
