// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/objectversion"
)

// ObjectVersionCreate is the builder for creating a ObjectVersion entity.
type ObjectVersionCreate struct {
	config
	mutation *ObjectVersionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ObjectVersionCreate) SetCreatedAt(v time.Time) *ObjectVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ObjectVersionCreate) SetNillableCreatedAt(v *time.Time) *ObjectVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ObjectVersionCreate) SetUpdatedAt(v time.Time) *ObjectVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ObjectVersionCreate) SetNillableUpdatedAt(v *time.Time) *ObjectVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetObjectID sets the "object_id" field.
func (_c *ObjectVersionCreate) SetObjectID(v string) *ObjectVersionCreate {
	_c.mutation.SetObjectID(v)
	return _c
}

// SetBlobID sets the "blob_id" field.
func (_c *ObjectVersionCreate) SetBlobID(v string) *ObjectVersionCreate {
	_c.mutation.SetBlobID(v)
	return _c
}

// SetRestoredFromVersionID sets the "restored_from_version_id" field.
func (_c *ObjectVersionCreate) SetRestoredFromVersionID(v string) *ObjectVersionCreate {
	_c.mutation.SetRestoredFromVersionID(v)
	return _c
}

// SetNillableRestoredFromVersionID sets the "restored_from_version_id" field if the given value is not nil.
func (_c *ObjectVersionCreate) SetNillableRestoredFromVersionID(v *string) *ObjectVersionCreate {
	if v != nil {
		_c.SetRestoredFromVersionID(*v)
	}
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *ObjectVersionCreate) SetCapturedAt(v time.Time) *ObjectVersionCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ObjectVersionCreate) SetID(v string) *ObjectVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ObjectVersionMutation object of the builder.
func (_c *ObjectVersionCreate) Mutation() *ObjectVersionMutation {
	return _c.mutation
}

// Save creates the ObjectVersion in the database.
func (_c *ObjectVersionCreate) Save(ctx context.Context) (*ObjectVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObjectVersionCreate) SaveX(ctx context.Context) *ObjectVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObjectVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := objectversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := objectversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObjectVersionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ObjectVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ObjectVersion.updated_at"`)}
	}
	if _, ok := _c.mutation.ObjectID(); !ok {
		return &ValidationError{Name: "object_id", err: errors.New(`ent: missing required field "ObjectVersion.object_id"`)}
	}
	if v, ok := _c.mutation.ObjectID(); ok {
		if err := objectversion.ObjectIDValidator(v); err != nil {
			return &ValidationError{Name: "object_id", err: fmt.Errorf(`ent: validator failed for field "ObjectVersion.object_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BlobID(); !ok {
		return &ValidationError{Name: "blob_id", err: errors.New(`ent: missing required field "ObjectVersion.blob_id"`)}
	}
	if v, ok := _c.mutation.BlobID(); ok {
		if err := objectversion.BlobIDValidator(v); err != nil {
			return &ValidationError{Name: "blob_id", err: fmt.Errorf(`ent: validator failed for field "ObjectVersion.blob_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CapturedAt(); !ok {
		return &ValidationError{Name: "captured_at", err: errors.New(`ent: missing required field "ObjectVersion.captured_at"`)}
	}
	return nil
}

func (_c *ObjectVersionCreate) sqlSave(ctx context.Context) (*ObjectVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ObjectVersion.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObjectVersionCreate) createSpec() (*ObjectVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &ObjectVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(objectversion.Table, sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(objectversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(objectversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ObjectID(); ok {
		_spec.SetField(objectversion.FieldObjectID, field.TypeString, value)
		_node.ObjectID = value
	}
	if value, ok := _c.mutation.BlobID(); ok {
		_spec.SetField(objectversion.FieldBlobID, field.TypeString, value)
		_node.BlobID = value
	}
	if value, ok := _c.mutation.RestoredFromVersionID(); ok {
		_spec.SetField(objectversion.FieldRestoredFromVersionID, field.TypeString, value)
		_node.RestoredFromVersionID = &value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(objectversion.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = value
	}
	return _node, _spec
}

// ObjectVersionCreateBulk is the builder for creating many ObjectVersion entities in bulk.
type ObjectVersionCreateBulk struct {
	config
	err      error
	builders []*ObjectVersionCreate
}

// Save creates the ObjectVersion entities in the database.
func (_c *ObjectVersionCreateBulk) Save(ctx context.Context) ([]*ObjectVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ObjectVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObjectVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObjectVersionCreateBulk) SaveX(ctx context.Context) []*ObjectVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
