// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/burrow/packages/engine/ent/object"
	"github.com/omkar273/burrow/packages/engine/ent/objectalias"
)

// ObjectAlias is the model entity for the ObjectAlias schema.
type ObjectAlias struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ObjectID holds the value of the "object_id" field.
	ObjectID string `json:"object_id,omitempty"`
	// SourceID holds the value of the "source_id" field.
	SourceID string `json:"source_id,omitempty"`
	// ExternalID holds the value of the "external_id" field.
	ExternalID string `json:"external_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ObjectAliasQuery when eager-loading is set.
	Edges        ObjectAliasEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ObjectAliasEdges holds the relations/edges for other nodes in the graph.
type ObjectAliasEdges struct {
	// Object holds the value of the object edge.
	Object *Object `json:"object,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ObjectOrErr returns the Object value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ObjectAliasEdges) ObjectOrErr() (*Object, error) {
	if e.Object != nil {
		return e.Object, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: object.Label}
	}
	return nil, &NotLoadedError{edge: "object"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ObjectAlias) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case objectalias.FieldID, objectalias.FieldObjectID, objectalias.FieldSourceID, objectalias.FieldExternalID:
			values[i] = new(sql.NullString)
		case objectalias.FieldCreatedAt, objectalias.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ObjectAlias fields.
func (_m *ObjectAlias) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case objectalias.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case objectalias.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case objectalias.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case objectalias.FieldObjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_id", values[i])
			} else if value.Valid {
				_m.ObjectID = value.String
			}
		case objectalias.FieldSourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_id", values[i])
			} else if value.Valid {
				_m.SourceID = value.String
			}
		case objectalias.FieldExternalID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field external_id", values[i])
			} else if value.Valid {
				_m.ExternalID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ObjectAlias.
// This includes values selected through modifiers, order, etc.
func (_m *ObjectAlias) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryObject queries the "object" edge of the ObjectAlias entity.
func (_m *ObjectAlias) QueryObject() *ObjectQuery {
	return NewObjectAliasClient(_m.config).QueryObject(_m)
}

// Update returns a builder for updating this ObjectAlias.
// Note that you need to call ObjectAlias.Unwrap() before calling this method if this ObjectAlias
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ObjectAlias) Update() *ObjectAliasUpdateOne {
	return NewObjectAliasClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ObjectAlias entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ObjectAlias) Unwrap() *ObjectAlias {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ObjectAlias is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ObjectAlias) String() string {
	var builder strings.Builder
	builder.WriteString("ObjectAlias(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("object_id=")
	builder.WriteString(_m.ObjectID)
	builder.WriteString(", ")
	builder.WriteString("source_id=")
	builder.WriteString(_m.SourceID)
	builder.WriteString(", ")
	builder.WriteString("external_id=")
	builder.WriteString(_m.ExternalID)
	builder.WriteByte(')')
	return builder.String()
}

// ObjectAliasSlice is a parsable slice of ObjectAlias.
type ObjectAliasSlice []*ObjectAlias
