// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/objectversion"
	"github.com/omkar273/burrow/packages/engine/ent/predicate"
)

// ObjectVersionUpdate is the builder for updating ObjectVersion entities.
type ObjectVersionUpdate struct {
	config
	hooks    []Hook
	mutation *ObjectVersionMutation
}

// Where appends a list predicates to the ObjectVersionUpdate builder.
func (_u *ObjectVersionUpdate) Where(ps ...predicate.ObjectVersion) *ObjectVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectVersionUpdate) SetUpdatedAt(v time.Time) *ObjectVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRestoredFromVersionID sets the "restored_from_version_id" field.
func (_u *ObjectVersionUpdate) SetRestoredFromVersionID(v string) *ObjectVersionUpdate {
	_u.mutation.SetRestoredFromVersionID(v)
	return _u
}

// SetNillableRestoredFromVersionID sets the "restored_from_version_id" field if the given value is not nil.
func (_u *ObjectVersionUpdate) SetNillableRestoredFromVersionID(v *string) *ObjectVersionUpdate {
	if v != nil {
		_u.SetRestoredFromVersionID(*v)
	}
	return _u
}

// ClearRestoredFromVersionID clears the value of the "restored_from_version_id" field.
func (_u *ObjectVersionUpdate) ClearRestoredFromVersionID() *ObjectVersionUpdate {
	_u.mutation.ClearRestoredFromVersionID()
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *ObjectVersionUpdate) SetCapturedAt(v time.Time) *ObjectVersionUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *ObjectVersionUpdate) SetNillableCapturedAt(v *time.Time) *ObjectVersionUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// Mutation returns the ObjectVersionMutation object of the builder.
func (_u *ObjectVersionUpdate) Mutation() *ObjectVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObjectVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObjectVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := objectversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObjectVersionUpdate) check() error {
	if _u.mutation.ObjectCleared() && len(_u.mutation.ObjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ObjectVersion.object"`)
	}
	if _u.mutation.BlobCleared() && len(_u.mutation.BlobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ObjectVersion.blob"`)
	}
	return nil
}

func (_u *ObjectVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(objectversion.Table, objectversion.Columns, sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(objectversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RestoredFromVersionID(); ok {
		_spec.SetField(objectversion.FieldRestoredFromVersionID, field.TypeString, value)
	}
	if _u.mutation.RestoredFromVersionIDCleared() {
		_spec.ClearField(objectversion.FieldRestoredFromVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(objectversion.FieldCapturedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{objectversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObjectVersionUpdateOne is the builder for updating a single ObjectVersion entity.
type ObjectVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ObjectVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectVersionUpdateOne) SetUpdatedAt(v time.Time) *ObjectVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRestoredFromVersionID sets the "restored_from_version_id" field.
func (_u *ObjectVersionUpdateOne) SetRestoredFromVersionID(v string) *ObjectVersionUpdateOne {
	_u.mutation.SetRestoredFromVersionID(v)
	return _u
}

// SetNillableRestoredFromVersionID sets the "restored_from_version_id" field if the given value is not nil.
func (_u *ObjectVersionUpdateOne) SetNillableRestoredFromVersionID(v *string) *ObjectVersionUpdateOne {
	if v != nil {
		_u.SetRestoredFromVersionID(*v)
	}
	return _u
}

// ClearRestoredFromVersionID clears the value of the "restored_from_version_id" field.
func (_u *ObjectVersionUpdateOne) ClearRestoredFromVersionID() *ObjectVersionUpdateOne {
	_u.mutation.ClearRestoredFromVersionID()
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *ObjectVersionUpdateOne) SetCapturedAt(v time.Time) *ObjectVersionUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *ObjectVersionUpdateOne) SetNillableCapturedAt(v *time.Time) *ObjectVersionUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// Mutation returns the ObjectVersionMutation object of the builder.
func (_u *ObjectVersionUpdateOne) Mutation() *ObjectVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ObjectVersionUpdate builder.
func (_u *ObjectVersionUpdateOne) Where(ps ...predicate.ObjectVersion) *ObjectVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObjectVersionUpdateOne) Select(field string, fields ...string) *ObjectVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ObjectVersion entity.
func (_u *ObjectVersionUpdateOne) Save(ctx context.Context) (*ObjectVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectVersionUpdateOne) SaveX(ctx context.Context) *ObjectVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObjectVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := objectversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ObjectVersionUpdateOne) check() error {
	if _u.mutation.ObjectCleared() && len(_u.mutation.ObjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ObjectVersion.object"`)
	}
	if _u.mutation.BlobCleared() && len(_u.mutation.BlobIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ObjectVersion.blob"`)
	}
	return nil
}

func (_u *ObjectVersionUpdateOne) sqlSave(ctx context.Context) (_node *ObjectVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(objectversion.Table, objectversion.Columns, sqlgraph.NewFieldSpec(objectversion.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ObjectVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, objectversion.FieldID)
		for _, f := range fields {
			if !objectversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != objectversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(objectversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RestoredFromVersionID(); ok {
		_spec.SetField(objectversion.FieldRestoredFromVersionID, field.TypeString, value)
	}
	if _u.mutation.RestoredFromVersionIDCleared() {
		_spec.ClearField(objectversion.FieldRestoredFromVersionID, field.TypeString)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(objectversion.FieldCapturedAt, field.TypeTime, value)
	}
	_node = &ObjectVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{objectversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
