// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/omkar273/burrow/packages/engine/ent/blob"
	"github.com/omkar273/burrow/packages/engine/ent/object"
	"github.com/omkar273/burrow/packages/engine/ent/objectalias"
	"github.com/omkar273/burrow/packages/engine/ent/objectversion"
	"github.com/omkar273/burrow/packages/engine/ent/schema"
	"github.com/omkar273/burrow/packages/engine/ent/source"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blobMixin := schema.Blob{}.Mixin()
	blobMixinFields0 := blobMixin[0].Fields()
	_ = blobMixinFields0
	blobFields := schema.Blob{}.Fields()
	_ = blobFields
	// blobDescCreatedAt is the schema descriptor for created_at field.
	blobDescCreatedAt := blobMixinFields0[0].Descriptor()
	// blob.DefaultCreatedAt holds the default value on creation for the created_at field.
	blob.DefaultCreatedAt = blobDescCreatedAt.Default.(func() time.Time)
	// blobDescUpdatedAt is the schema descriptor for updated_at field.
	blobDescUpdatedAt := blobMixinFields0[1].Descriptor()
	// blob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blob.DefaultUpdatedAt = blobDescUpdatedAt.Default.(func() time.Time)
	// blob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blob.UpdateDefaultUpdatedAt = blobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blobDescContentHash is the schema descriptor for content_hash field.
	blobDescContentHash := blobFields[1].Descriptor()
	// blob.ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	blob.ContentHashValidator = blobDescContentHash.Validators[0].(func(string) error)
	// blobDescSizeBytes is the schema descriptor for size_bytes field.
	blobDescSizeBytes := blobFields[2].Descriptor()
	// blob.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	blob.SizeBytesValidator = blobDescSizeBytes.Validators[0].(func(int64) error)
	objectMixin := schema.Object{}.Mixin()
	objectMixinFields0 := objectMixin[0].Fields()
	_ = objectMixinFields0
	objectFields := schema.Object{}.Fields()
	_ = objectFields
	// objectDescCreatedAt is the schema descriptor for created_at field.
	objectDescCreatedAt := objectMixinFields0[0].Descriptor()
	// object.DefaultCreatedAt holds the default value on creation for the created_at field.
	object.DefaultCreatedAt = objectDescCreatedAt.Default.(func() time.Time)
	// objectDescUpdatedAt is the schema descriptor for updated_at field.
	objectDescUpdatedAt := objectMixinFields0[1].Descriptor()
	// object.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	object.DefaultUpdatedAt = objectDescUpdatedAt.Default.(func() time.Time)
	// object.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	object.UpdateDefaultUpdatedAt = objectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// objectDescSourceID is the schema descriptor for source_id field.
	objectDescSourceID := objectFields[1].Descriptor()
	// object.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	object.SourceIDValidator = objectDescSourceID.Validators[0].(func(string) error)
	// objectDescKind is the schema descriptor for kind field.
	objectDescKind := objectFields[2].Descriptor()
	// object.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	object.KindValidator = objectDescKind.Validators[0].(func(string) error)
	// objectDescExternalID is the schema descriptor for external_id field.
	objectDescExternalID := objectFields[3].Descriptor()
	// object.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	object.ExternalIDValidator = objectDescExternalID.Validators[0].(func(string) error)
	objectaliasMixin := schema.ObjectAlias{}.Mixin()
	objectaliasMixinFields0 := objectaliasMixin[0].Fields()
	_ = objectaliasMixinFields0
	objectaliasFields := schema.ObjectAlias{}.Fields()
	_ = objectaliasFields
	// objectaliasDescCreatedAt is the schema descriptor for created_at field.
	objectaliasDescCreatedAt := objectaliasMixinFields0[0].Descriptor()
	// objectalias.DefaultCreatedAt holds the default value on creation for the created_at field.
	objectalias.DefaultCreatedAt = objectaliasDescCreatedAt.Default.(func() time.Time)
	// objectaliasDescUpdatedAt is the schema descriptor for updated_at field.
	objectaliasDescUpdatedAt := objectaliasMixinFields0[1].Descriptor()
	// objectalias.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	objectalias.DefaultUpdatedAt = objectaliasDescUpdatedAt.Default.(func() time.Time)
	// objectalias.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	objectalias.UpdateDefaultUpdatedAt = objectaliasDescUpdatedAt.UpdateDefault.(func() time.Time)
	// objectaliasDescObjectID is the schema descriptor for object_id field.
	objectaliasDescObjectID := objectaliasFields[1].Descriptor()
	// objectalias.ObjectIDValidator is a validator for the "object_id" field. It is called by the builders before save.
	objectalias.ObjectIDValidator = objectaliasDescObjectID.Validators[0].(func(string) error)
	// objectaliasDescSourceID is the schema descriptor for source_id field.
	objectaliasDescSourceID := objectaliasFields[2].Descriptor()
	// objectalias.SourceIDValidator is a validator for the "source_id" field. It is called by the builders before save.
	objectalias.SourceIDValidator = objectaliasDescSourceID.Validators[0].(func(string) error)
	// objectaliasDescExternalID is the schema descriptor for external_id field.
	objectaliasDescExternalID := objectaliasFields[3].Descriptor()
	// objectalias.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	objectalias.ExternalIDValidator = objectaliasDescExternalID.Validators[0].(func(string) error)
	objectversionMixin := schema.ObjectVersion{}.Mixin()
	objectversionMixinFields0 := objectversionMixin[0].Fields()
	_ = objectversionMixinFields0
	objectversionFields := schema.ObjectVersion{}.Fields()
	_ = objectversionFields
	// objectversionDescCreatedAt is the schema descriptor for created_at field.
	objectversionDescCreatedAt := objectversionMixinFields0[0].Descriptor()
	// objectversion.DefaultCreatedAt holds the default value on creation for the created_at field.
	objectversion.DefaultCreatedAt = objectversionDescCreatedAt.Default.(func() time.Time)
	// objectversionDescUpdatedAt is the schema descriptor for updated_at field.
	objectversionDescUpdatedAt := objectversionMixinFields0[1].Descriptor()
	// objectversion.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	objectversion.DefaultUpdatedAt = objectversionDescUpdatedAt.Default.(func() time.Time)
	// objectversion.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	objectversion.UpdateDefaultUpdatedAt = objectversionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// objectversionDescObjectID is the schema descriptor for object_id field.
	objectversionDescObjectID := objectversionFields[1].Descriptor()
	// objectversion.ObjectIDValidator is a validator for the "object_id" field. It is called by the builders before save.
	objectversion.ObjectIDValidator = objectversionDescObjectID.Validators[0].(func(string) error)
	// objectversionDescBlobID is the schema descriptor for blob_id field.
	objectversionDescBlobID := objectversionFields[2].Descriptor()
	// objectversion.BlobIDValidator is a validator for the "blob_id" field. It is called by the builders before save.
	objectversion.BlobIDValidator = objectversionDescBlobID.Validators[0].(func(string) error)
	sourceMixin := schema.Source{}.Mixin()
	sourceMixinFields0 := sourceMixin[0].Fields()
	_ = sourceMixinFields0
	sourceFields := schema.Source{}.Fields()
	_ = sourceFields
	// sourceDescCreatedAt is the schema descriptor for created_at field.
	sourceDescCreatedAt := sourceMixinFields0[0].Descriptor()
	// source.DefaultCreatedAt holds the default value on creation for the created_at field.
	source.DefaultCreatedAt = sourceDescCreatedAt.Default.(func() time.Time)
	// sourceDescUpdatedAt is the schema descriptor for updated_at field.
	sourceDescUpdatedAt := sourceMixinFields0[1].Descriptor()
	// source.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	source.DefaultUpdatedAt = sourceDescUpdatedAt.Default.(func() time.Time)
	// source.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	source.UpdateDefaultUpdatedAt = sourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sourceDescKind is the schema descriptor for kind field.
	sourceDescKind := sourceFields[1].Descriptor()
	// source.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	source.KindValidator = sourceDescKind.Validators[0].(func(string) error)
	// sourceDescAccountEmail is the schema descriptor for account_email field.
	sourceDescAccountEmail := sourceFields[2].Descriptor()
	// source.AccountEmailValidator is a validator for the "account_email" field. It is called by the builders before save.
	source.AccountEmailValidator = sourceDescAccountEmail.Validators[0].(func(string) error)
	// sourceDescStatus is the schema descriptor for status field.
	sourceDescStatus := sourceFields[3].Descriptor()
	// source.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	source.StatusValidator = sourceDescStatus.Validators[0].(func(string) error)
}
