// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/packages/engine/ent/object"
	"github.com/omkar273/burrow/packages/engine/ent/predicate"
	"github.com/omkar273/burrow/packages/engine/ent/source"
)

// SourceUpdate is the builder for updating Source entities.
type SourceUpdate struct {
	config
	hooks    []Hook
	mutation *SourceMutation
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdate) Where(ps ...predicate.Source) *SourceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdate) SetUpdatedAt(v time.Time) *SourceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountEmail sets the "account_email" field.
func (_u *SourceUpdate) SetAccountEmail(v string) *SourceUpdate {
	_u.mutation.SetAccountEmail(v)
	return _u
}

// SetNillableAccountEmail sets the "account_email" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableAccountEmail(v *string) *SourceUpdate {
	if v != nil {
		_u.SetAccountEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SourceUpdate) SetStatus(v string) *SourceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SourceUpdate) SetNillableStatus(v *string) *SourceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddObjectIDs adds the "objects" edge to the Object entity by IDs.
func (_u *SourceUpdate) AddObjectIDs(ids ...string) *SourceUpdate {
	_u.mutation.AddObjectIDs(ids...)
	return _u
}

// AddObjects adds the "objects" edges to the Object entity.
func (_u *SourceUpdate) AddObjects(v ...*Object) *SourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddObjectIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdate) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearObjects clears all "objects" edges to the Object entity.
func (_u *SourceUpdate) ClearObjects() *SourceUpdate {
	_u.mutation.ClearObjects()
	return _u
}

// RemoveObjectIDs removes the "objects" edge to Object entities by IDs.
func (_u *SourceUpdate) RemoveObjectIDs(ids ...string) *SourceUpdate {
	_u.mutation.RemoveObjectIDs(ids...)
	return _u
}

// RemoveObjects removes "objects" edges to Object entities.
func (_u *SourceUpdate) RemoveObjects(v ...*Object) *SourceUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveObjectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SourceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SourceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdate) check() error {
	if v, ok := _u.mutation.AccountEmail(); ok {
		if err := source.AccountEmailValidator(v); err != nil {
			return &ValidationError{Name: "account_email", err: fmt.Errorf(`ent: validator failed for field "Source.account_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := source.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Source.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountEmail(); ok {
		_spec.SetField(source.FieldAccountEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(source.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ObjectsTable,
			Columns: []string{source.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(object.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedObjectsIDs(); len(nodes) > 0 && !_u.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ObjectsTable,
			Columns: []string{source.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(object.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ObjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ObjectsTable,
			Columns: []string{source.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(object.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SourceUpdateOne is the builder for updating a single Source entity.
type SourceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SourceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SourceUpdateOne) SetUpdatedAt(v time.Time) *SourceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccountEmail sets the "account_email" field.
func (_u *SourceUpdateOne) SetAccountEmail(v string) *SourceUpdateOne {
	_u.mutation.SetAccountEmail(v)
	return _u
}

// SetNillableAccountEmail sets the "account_email" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableAccountEmail(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetAccountEmail(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SourceUpdateOne) SetStatus(v string) *SourceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SourceUpdateOne) SetNillableStatus(v *string) *SourceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddObjectIDs adds the "objects" edge to the Object entity by IDs.
func (_u *SourceUpdateOne) AddObjectIDs(ids ...string) *SourceUpdateOne {
	_u.mutation.AddObjectIDs(ids...)
	return _u
}

// AddObjects adds the "objects" edges to the Object entity.
func (_u *SourceUpdateOne) AddObjects(v ...*Object) *SourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddObjectIDs(ids...)
}

// Mutation returns the SourceMutation object of the builder.
func (_u *SourceUpdateOne) Mutation() *SourceMutation {
	return _u.mutation
}

// ClearObjects clears all "objects" edges to the Object entity.
func (_u *SourceUpdateOne) ClearObjects() *SourceUpdateOne {
	_u.mutation.ClearObjects()
	return _u
}

// RemoveObjectIDs removes the "objects" edge to Object entities by IDs.
func (_u *SourceUpdateOne) RemoveObjectIDs(ids ...string) *SourceUpdateOne {
	_u.mutation.RemoveObjectIDs(ids...)
	return _u
}

// RemoveObjects removes "objects" edges to Object entities.
func (_u *SourceUpdateOne) RemoveObjects(v ...*Object) *SourceUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveObjectIDs(ids...)
}

// Where appends a list predicates to the SourceUpdate builder.
func (_u *SourceUpdateOne) Where(ps ...predicate.Source) *SourceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SourceUpdateOne) Select(field string, fields ...string) *SourceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Source entity.
func (_u *SourceUpdateOne) Save(ctx context.Context) (*Source, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SourceUpdateOne) SaveX(ctx context.Context) *Source {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SourceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SourceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SourceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := source.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SourceUpdateOne) check() error {
	if v, ok := _u.mutation.AccountEmail(); ok {
		if err := source.AccountEmailValidator(v); err != nil {
			return &ValidationError{Name: "account_email", err: fmt.Errorf(`ent: validator failed for field "Source.account_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := source.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Source.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SourceUpdateOne) sqlSave(ctx context.Context) (_node *Source, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(source.Table, source.Columns, sqlgraph.NewFieldSpec(source.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Source.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, source.FieldID)
		for _, f := range fields {
			if !source.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != source.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(source.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AccountEmail(); ok {
		_spec.SetField(source.FieldAccountEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(source.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ObjectsTable,
			Columns: []string{source.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(object.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedObjectsIDs(); len(nodes) > 0 && !_u.mutation.ObjectsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ObjectsTable,
			Columns: []string{source.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(object.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ObjectsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   source.ObjectsTable,
			Columns: []string{source.ObjectsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(object.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Source{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{source.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
