// Code generated by ent, DO NOT EDIT.

package source

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/omkar273/burrow/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldUpdatedAt, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldKind, v))
}

// AccountEmail applies equality check predicate on the "account_email" field. It's identical to AccountEmailEQ.
func AccountEmail(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldAccountEmail, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldUpdatedAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldKind, v))
}

// AccountEmailEQ applies the EQ predicate on the "account_email" field.
func AccountEmailEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldAccountEmail, v))
}

// AccountEmailNEQ applies the NEQ predicate on the "account_email" field.
func AccountEmailNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldAccountEmail, v))
}

// AccountEmailIn applies the In predicate on the "account_email" field.
func AccountEmailIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldAccountEmail, vs...))
}

// AccountEmailNotIn applies the NotIn predicate on the "account_email" field.
func AccountEmailNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldAccountEmail, vs...))
}

// AccountEmailGT applies the GT predicate on the "account_email" field.
func AccountEmailGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldAccountEmail, v))
}

// AccountEmailGTE applies the GTE predicate on the "account_email" field.
func AccountEmailGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldAccountEmail, v))
}

// AccountEmailLT applies the LT predicate on the "account_email" field.
func AccountEmailLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldAccountEmail, v))
}

// AccountEmailLTE applies the LTE predicate on the "account_email" field.
func AccountEmailLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldAccountEmail, v))
}

// AccountEmailContains applies the Contains predicate on the "account_email" field.
func AccountEmailContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldAccountEmail, v))
}

// AccountEmailHasPrefix applies the HasPrefix predicate on the "account_email" field.
func AccountEmailHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldAccountEmail, v))
}

// AccountEmailHasSuffix applies the HasSuffix predicate on the "account_email" field.
func AccountEmailHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldAccountEmail, v))
}

// AccountEmailEqualFold applies the EqualFold predicate on the "account_email" field.
func AccountEmailEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldAccountEmail, v))
}

// AccountEmailContainsFold applies the ContainsFold predicate on the "account_email" field.
func AccountEmailContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldAccountEmail, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Source {
	return predicate.Source(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Source {
	return predicate.Source(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Source {
	return predicate.Source(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Source {
	return predicate.Source(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Source {
	return predicate.Source(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Source {
	return predicate.Source(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Source {
	return predicate.Source(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Source {
	return predicate.Source(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Source {
	return predicate.Source(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Source {
	return predicate.Source(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Source) predicate.Source {
	return predicate.Source(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Source) predicate.Source {
	return predicate.Source(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Source) predicate.Source {
	return predicate.Source(sql.NotPredicates(p))
}
