// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/ent/objectalias"
)

// ObjectAliasCreate is the builder for creating a ObjectAlias entity.
type ObjectAliasCreate struct {
	config
	mutation *ObjectAliasMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ObjectAliasCreate) SetCreatedAt(v time.Time) *ObjectAliasCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ObjectAliasCreate) SetNillableCreatedAt(v *time.Time) *ObjectAliasCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ObjectAliasCreate) SetUpdatedAt(v time.Time) *ObjectAliasCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ObjectAliasCreate) SetNillableUpdatedAt(v *time.Time) *ObjectAliasCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetObjectID sets the "object_id" field.
func (_c *ObjectAliasCreate) SetObjectID(v string) *ObjectAliasCreate {
	_c.mutation.SetObjectID(v)
	return _c
}

// SetSourceID sets the "source_id" field.
func (_c *ObjectAliasCreate) SetSourceID(v string) *ObjectAliasCreate {
	_c.mutation.SetSourceID(v)
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *ObjectAliasCreate) SetExternalID(v string) *ObjectAliasCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ObjectAliasCreate) SetID(v string) *ObjectAliasCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ObjectAliasMutation object of the builder.
func (_c *ObjectAliasCreate) Mutation() *ObjectAliasMutation {
	return _c.mutation
}

// Save creates the ObjectAlias in the database.
func (_c *ObjectAliasCreate) Save(ctx context.Context) (*ObjectAlias, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObjectAliasCreate) SaveX(ctx context.Context) *ObjectAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectAliasCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectAliasCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObjectAliasCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := objectalias.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := objectalias.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObjectAliasCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ObjectAlias.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ObjectAlias.updated_at"`)}
	}
	if _, ok := _c.mutation.ObjectID(); !ok {
		return &ValidationError{Name: "object_id", err: errors.New(`ent: missing required field "ObjectAlias.object_id"`)}
	}
	if v, ok := _c.mutation.ObjectID(); ok {
		if err := objectalias.ObjectIDValidator(v); err != nil {
			return &ValidationError{Name: "object_id", err: fmt.Errorf(`ent: validator failed for field "ObjectAlias.object_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceID(); !ok {
		return &ValidationError{Name: "source_id", err: errors.New(`ent: missing required field "ObjectAlias.source_id"`)}
	}
	if v, ok := _c.mutation.SourceID(); ok {
		if err := objectalias.SourceIDValidator(v); err != nil {
			return &ValidationError{Name: "source_id", err: fmt.Errorf(`ent: validator failed for field "ObjectAlias.source_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "ObjectAlias.external_id"`)}
	}
	if v, ok := _c.mutation.ExternalID(); ok {
		if err := objectalias.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "ObjectAlias.external_id": %w`, err)}
		}
	}
	return nil
}

func (_c *ObjectAliasCreate) sqlSave(ctx context.Context) (*ObjectAlias, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ObjectAlias.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObjectAliasCreate) createSpec() (*ObjectAlias, *sqlgraph.CreateSpec) {
	var (
		_node = &ObjectAlias{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(objectalias.Table, sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(objectalias.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(objectalias.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ObjectID(); ok {
		_spec.SetField(objectalias.FieldObjectID, field.TypeString, value)
		_node.ObjectID = value
	}
	if value, ok := _c.mutation.SourceID(); ok {
		_spec.SetField(objectalias.FieldSourceID, field.TypeString, value)
		_node.SourceID = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(objectalias.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	return _node, _spec
}

// ObjectAliasCreateBulk is the builder for creating many ObjectAlias entities in bulk.
type ObjectAliasCreateBulk struct {
	config
	err      error
	builders []*ObjectAliasCreate
}

// Save creates the ObjectAlias entities in the database.
func (_c *ObjectAliasCreateBulk) Save(ctx context.Context) ([]*ObjectAlias, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ObjectAlias, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObjectAliasMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObjectAliasCreateBulk) SaveX(ctx context.Context) []*ObjectAlias {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectAliasCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectAliasCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
