// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/omkar273/burrow/ent/objectalias"
	"github.com/omkar273/burrow/ent/predicate"
)

// ObjectAliasUpdate is the builder for updating ObjectAlias entities.
type ObjectAliasUpdate struct {
	config
	hooks    []Hook
	mutation *ObjectAliasMutation
}

// Where appends a list predicates to the ObjectAliasUpdate builder.
func (_u *ObjectAliasUpdate) Where(ps ...predicate.ObjectAlias) *ObjectAliasUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectAliasUpdate) SetUpdatedAt(v time.Time) *ObjectAliasUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ObjectAliasMutation object of the builder.
func (_u *ObjectAliasUpdate) Mutation() *ObjectAliasMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObjectAliasUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectAliasUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObjectAliasUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectAliasUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectAliasUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := objectalias.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ObjectAliasUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(objectalias.Table, objectalias.Columns, sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(objectalias.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{objectalias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObjectAliasUpdateOne is the builder for updating a single ObjectAlias entity.
type ObjectAliasUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ObjectAliasMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObjectAliasUpdateOne) SetUpdatedAt(v time.Time) *ObjectAliasUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ObjectAliasMutation object of the builder.
func (_u *ObjectAliasUpdateOne) Mutation() *ObjectAliasMutation {
	return _u.mutation
}

// Where appends a list predicates to the ObjectAliasUpdate builder.
func (_u *ObjectAliasUpdateOne) Where(ps ...predicate.ObjectAlias) *ObjectAliasUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObjectAliasUpdateOne) Select(field string, fields ...string) *ObjectAliasUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ObjectAlias entity.
func (_u *ObjectAliasUpdateOne) Save(ctx context.Context) (*ObjectAlias, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObjectAliasUpdateOne) SaveX(ctx context.Context) *ObjectAlias {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObjectAliasUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObjectAliasUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObjectAliasUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := objectalias.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ObjectAliasUpdateOne) sqlSave(ctx context.Context) (_node *ObjectAlias, err error) {
	_spec := sqlgraph.NewUpdateSpec(objectalias.Table, objectalias.Columns, sqlgraph.NewFieldSpec(objectalias.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ObjectAlias.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, objectalias.FieldID)
		for _, f := range fields {
			if !objectalias.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != objectalias.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(objectalias.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ObjectAlias{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{objectalias.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
