// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/omkar273/burrow/ent/blob"
	"github.com/omkar273/burrow/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blobMixin := schema.Blob{}.Mixin()
	blobMixinFields0 := blobMixin[0].Fields()
	_ = blobMixinFields0
	blobFields := schema.Blob{}.Fields()
	_ = blobFields
	// blobDescCreatedAt is the schema descriptor for created_at field.
	blobDescCreatedAt := blobMixinFields0[0].Descriptor()
	// blob.DefaultCreatedAt holds the default value on creation for the created_at field.
	blob.DefaultCreatedAt = blobDescCreatedAt.Default.(func() time.Time)
	// blobDescUpdatedAt is the schema descriptor for updated_at field.
	blobDescUpdatedAt := blobMixinFields0[1].Descriptor()
	// blob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blob.DefaultUpdatedAt = blobDescUpdatedAt.Default.(func() time.Time)
	// blob.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blob.UpdateDefaultUpdatedAt = blobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blobDescContentHash is the schema descriptor for content_hash field.
	blobDescContentHash := blobFields[1].Descriptor()
	// blob.ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	blob.ContentHashValidator = blobDescContentHash.Validators[0].(func(string) error)
	// blobDescSizeBytes is the schema descriptor for size_bytes field.
	blobDescSizeBytes := blobFields[2].Descriptor()
	// blob.SizeBytesValidator is a validator for the "size_bytes" field. It is called by the builders before save.
	blob.SizeBytesValidator = blobDescSizeBytes.Validators[0].(func(int64) error)
}
