// Code generated by ent, DO NOT EDIT.

package objectversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the objectversion type in the database.
	Label = "object_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldObjectID holds the string denoting the object_id field in the database.
	FieldObjectID = "object_id"
	// FieldBlobID holds the string denoting the blob_id field in the database.
	FieldBlobID = "blob_id"
	// FieldRestoredFromVersionID holds the string denoting the restored_from_version_id field in the database.
	FieldRestoredFromVersionID = "restored_from_version_id"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// Table holds the table name of the objectversion in the database.
	Table = "object_versions"
)

// Columns holds all SQL columns for objectversion fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldObjectID,
	FieldBlobID,
	FieldRestoredFromVersionID,
	FieldCapturedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ObjectIDValidator is a validator for the "object_id" field. It is called by the builders before save.
	ObjectIDValidator func(string) error
	// BlobIDValidator is a validator for the "blob_id" field. It is called by the builders before save.
	BlobIDValidator func(string) error
)

// OrderOption defines the ordering options for the ObjectVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByObjectID orders the results by the object_id field.
func ByObjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectID, opts...).ToFunc()
}

// ByBlobID orders the results by the blob_id field.
func ByBlobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlobID, opts...).ToFunc()
}

// ByRestoredFromVersionID orders the results by the restored_from_version_id field.
func ByRestoredFromVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRestoredFromVersionID, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}
